version: '3'

services:
     nginx_web:
         restart: always
         container_name: nginx_container
         image: nginx:latest
         ports:
             - 443:443  
         volumes:
             - ./nginx_setup/nginx.conf:/etc/nginx/nginx.conf
             - ./nginx_setup/certs/challenge_task.com.crt:/etc/ssl/challenge_task.com.crt
             - ./nginx_setup/certs/challenge_task.com.key:/etc/ssl/challenge_task.com.key
             - ./nginx_setup/logs:/etc/nginx/logs
             - ./nginx_setup/index.html:/etc/nginx/html/index.html
