version: '3'

services:
     nginx_web:
         restart: always
         container_name: nginx_container
         image: nginx:latest
         ports:
             - 80:80 
         volumes:
             - ./nginx_setup/nginx.conf:/etc/nginx/nginx.conf
             - ./nginx_setup/logs:/etc/nginx/logs
             - ./nginx_setup/index.html:/etc/nginx/html/index.html
